# Generated by Django 3.2.16 on 2024-01-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerieslist',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='grocerieslist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='GroceriesList',
        ),
    ]
